"""Tests for the public artifact hygiene guard."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.check_public_artifacts import check_text


def assert_clean(text):
    assert check_text("artifact.md", text, ".md") == []


def assert_blocks(text, expected):
    findings = check_text("artifact.md", text, ".md")
    assert findings
    assert any(expected in finding for finding in findings)


def test_clean_public_artifact_passes():
    assert_clean("Use EXAMPLE_PASSWORD and environment variables in docs.\n")


def test_literal_escaped_newline_is_blocked():
    assert_blocks("first" + "\\\\n" + "second\n", "literal escaped newline")


def test_local_path_is_blocked():
    assert_blocks("trace: " + "/home/" + "alice/project/file.txt\n", "local home path")


def test_internal_workflow_terms_are_blocked():
    assert_blocks("Generated by " + "Open" + "Claw" + " automation.\n", "internal automation marker")


def test_secret_assignment_is_blocked():
    value = "a" * 32
    assert_blocks("private_key = '" + value + "'\n", "secret-looking assignment")


def test_placeholder_secret_assignment_passes():
    assert_clean("private_key = 'EXAMPLE_PRIVATE_KEY'\n")
